---
experiences:
  - experience_name: Teladoc Health,
    experience_titles:
      - title: Senior Software Engineer,
        start: 03/2021,
        end: null
      - title: Software Engineer,
        start: 03/2020,
        end: 03/2021
      - title: Associate Software Engineer,
        start: 12/2018,
        end: 03/2020
      - title: Software Engineer (Contract),
        start: 01/2018,
        end: 12/2018
    summary: > 
      Direct and guide software engineering teams in software design and architecture, 
      lead and mentor, ensure delivery and execution of quality projects, and assist in 
      managing project resourcing and operations.
    accomplishments:
      - >
        Lead a team of over 8 engineers to successfully launch a massive project that single handedly 
        changed the fundamental relationship between a 
        Teladoc Health Member (the users that speak with our doctors over our virtual mediums) 
        and their benefits (products, ie Virtual Mental Health visits, a Member has access to). 
        This project, at launch, improved the user experience of over 25% of Teladoc Health Members and set the 
        pavement for smarter and improved scalable integrations with all of Teladoc Health's acquisitions.
      - > 
        Facilitated major improvements to one of our major codebase that reduced the 
        boilerplate code necessary to service newly acquired clients. This resulted 
        in reduced development time from 2-3 months to 1-2 months, 
        thus servicing new clients up to two months faster.
      - >
        Designed and lead an effort in implementing a scalable and configurable solution that allows 
        software engineering teams to easily create &quot;branded&quot; Telemedicine services. 
        This helped deliver client deliverables weeks, if not months, faster.
      - >
        Enhanced video conference experience and video conference logging. Ultimately, this helped 
        decrease canceled visits due to technical issues by over 10% and increased our confidence on 
        detecting and ease to debug/fix future production issues involving video conferences.
      - >
        Spearheaded WCAG initiative to help make the member website accessible to all users irrespective 
        of disability. With this work Teladoc received a WCAG compliance certification.
  - experience_name: NuCamp Bootcamp
    experience_titles:
      - title: Code Instructor
      - start: 02/2022
      - end: null
    summary: >
      Code instructor at NuCamp Bootcamp, a technical "bootcamp" for adults looking to become Software Engineers.
    accomplishments:
      - >
      Taught over 5 courses ranging from "HTML, CSS and Javacript" to more advanced courses like "React" averaging
      a student rating over 4.6/5
skills:
  - name: Object Oriented Programming
    examples:
      - Java
      - Javascript
      - Python
      - Ruby
      - Scala
  - name: Libraries & Framework
    examples:
      - Android Studios
      - Node.js
      - Play Framework
      - React.js
      - Ruby on Rails
  - name: Devops & Infrastructure
    examples:
      - AWS
      - Azure
      - Jenkins
      - Linux/Unix
      - Shell Scripting
  - name: Project Management
    examples: null
  - name: Fluent in Spanish
    examples: null
