# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install yarn
        run: npm install -g yarn && yarn set version berry
        
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Build for prod'
          add: 'build index.html'

    
